version: '3'
services:
  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt:11.5.2@sha256:14ecba1b29f4eaa571c711308fd8f249f0316627d8a3e0f22db827c733225c25
    networks:
      - external
    stop_signal: SIGINT
    devices:
      - /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/ttyUSB0
#      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0
    volumes:
      - ${APPDATA}/zwavejs:/usr/src/app/store
    ports:
      - 3011:3000
    labels:
      namespace: home
      port: 8091
      host: zwave.${SERVER_DOMAIN}
