version: '3'
services:
  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt:11.1.0@sha256:a11ff4e2e106ca99666cc7c4ad2510f3e58fe6fa8cd14c323539bc1090ac7cb7
    networks:
      - external
    stop_signal: SIGINT
    devices:
      - /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/ttyUSB0
#      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0
    volumes:
      - ${APPDATA}/zwavejs:/usr/src/app/store
    ports:
      - 3011:3000
    labels:
      namespace: home
      port: 8091
      host: zwave.${SERVER_DOMAIN}
