version: '3'
services:
  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt:10.1.3@sha256:ced70b4d3e2d393863e383e9e3b1f02d07596ac19d017fbea3a4f7f29d98a115
    networks:
      - external
    stop_signal: SIGINT
    devices:
      - /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/ttyUSB0
#      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0
    volumes:
      - ${APPDATA}/zwavejs:/usr/src/app/store
    ports:
      - 3011:3000
    labels:
      namespace: home
      port: 8091
      host: zwave.${SERVER_DOMAIN}
